### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by uPorter** [MMonkeyKiller/CustomBlocks#2]
When the noteblock is naturally placed with the worldgenerator, the item does not come when it is broken.

**Comment by uPorter** [comment]
`java.lang.NullPointerException: null
	at me.monkeykiller.customblocks.listeners.Events.onBlockBreak(Events.java:210) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor360.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:357) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:310) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:270) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1472) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1193) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1186) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1162) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Tuinity-"4ff2d15"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
`

When I try to break naturally occurring blocks, I get an error message like this
